import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import RequireClub from '@/components/RequireClub';
import TopNav from '@/components/TopNav';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );

export default function AppLayout({ children }) {
  return (
    <RequireClub>
      <TopNav />
      <main style={{ padding: 24, color: '#e5e7eb', background: '#0b0f19', minHeight: '100vh' }}>
        {children}
      </main>
    </RequireClub>
  );
}
